name: "DBUS API (Donostia)"
version: "1.0.2"
slug: "dbus_api"
description: "Backend REST no oficial con los tiempos de espera de autobús de DBUS Donostia (dbus.eus), para la integración dbus_donostia"
url: "https://github.com/tu-usuario-github/ha-dbus-addons"
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: application
boot: auto
host_network: false
ports:
  3000/tcp: 8081
ports_description:
  3000/tcp: "API HTTP (usa http://<IP_DE_HA>:8081 en la integración dbus_donostia)"
map: []
